---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
  pull_request:

permissions:
  contents: read

jobs:
  super-lint:
    name: Super-linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-linter
        uses: super-linter/super-linter@61abc07d755095a68f4987d1c2c3d1d64408f1f9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
